# Negative sampling

In [3]:
import numpy                 as np
import pandas                as pd
import matplotlib.pyplot     as plt
import seaborn               as sns
import sklearn.metrics       as Metrics
import pandas                as pd
import matplotlib            as mpl
import random
from calendar import monthrange

# import folium  
# from folium.plugins import HeatMap
# import branca

In [4]:
import json
import requests
import os
import calendar
import datetime

In [5]:
# set matplotlib defaults
%matplotlib inline
sns.set()
plt.rcParams["figure.figsize"] = (15,6)
mpl.rc('axes', labelsize=18)
mpl.rc('xtick', labelsize=16)
mpl.rc('ytick', labelsize=16)
plt.rc('figure', titlesize=18)
plt.style.use('seaborn-darkgrid')

## Data loading and preparation

In [6]:
# read dataset.accidents
data_folder = '../data'
accidents_file = os.path.join(data_folder, 'siniestros_bogota_historico.csv')
accidents = pd.read_csv(accidents_file,sep=',')
accidents.head()

,X,Y,OBJECTID,FORMULARIO,CODIGO_ACCIDENTE,ANO_OCURRENCIA_ACC,DIRECCION,GRAVEDAD,CLASE_ACC,LOCALIDAD_GEO,LOCALIDAD,FECHA_HORA_ACC,CIV,PK_CALZADA
0,-74.039690,4.759877,1001,A00728405,360471,2010,AK 18A-CL 182 58,SOLO DANOS,CHOQUE,USAQUEN,USAQUEN,2010-05-25T20:10:00.000Z,1007130.0,91019224.0
1,-74.114296,4.615476,1002,A00408972,305838,2008,TR 49-3 02,SOLO DANOS,CHOQUE,PUENTE ARANDA,PUENTE ARANDA,2008-09-30T07:00:00.000Z,16004607.0,195361.0
2,-74.105296,4.509792,1003,A000341903,4437952,2016,CL 80A-KR 1 SE 02,CON HERIDOS,CHOQUE,USME,USME,2016-02-27T16:20:00.000Z,5002841.0,149316.0
3,-74.167225,4.631051,1004,A000554581,4472304,2017,AV AVENIDA CIUDAD DE CALI-CL 42 S 02,CON HERIDOS,ATROPELLO,KENNEDY,KENNEDY,2017-02-09T16:45:00.000Z,8004447.0,66217.0
4,-74.121790,4.603106,1005,A000763908,4512837,2018,AV AVENIDA PRIMERA DE MAYO-KR 50A 14,CON HERIDOS,CHOQUE,PUENTE ARANDA,PUENTE ARANDA,2018-03-25T12:10:00.000Z,16003102.0,239094.0

In [7]:
# read dataset.weather
data_folder = '../data'
weather_data = os.path.join(data_folder, 'total.csv')
weather = pd.read_csv(weather_data,sep=',')
weather.head()

C:\Users\User\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,time,summary,icon,precipIntensity,precipProbability,temperature,apparentTemperature,dewPoint,humidity,...,windBearing,cloudCover,uvIndex,visibility,location,pressure,windGust,precipType,ozone,precipAccumulation
0,0,2017-10-27 05:00:00,Clear,clear-night,0.0,0.0,7.0,6.22,6.99,1.00,...,320.0,0.00,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN
1,1,2017-10-27 06:00:00,Clear,clear-night,0.0,0.0,7.0,6.22,6.00,0.93,...,320.0,0.13,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN
2,2,2017-10-27 07:00:00,Partly Cloudy,partly-cloudy-night,0.0,0.0,7.0,6.22,6.99,1.00,...,0.0,0.44,0.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN
3,3,2017-10-27 08:00:00,Partly Cloudy,partly-cloudy-night,0.0,0.0,9.0,8.51,9.00,1.00,...,0.0,0.44,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN
4,4,2017-10-27 09:00:00,Mostly Cloudy,partly-cloudy-night,0.0,0.0,10.0,10.00,9.99,1.00,...,251.0,0.75,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN

In [8]:
weather.columns

Index(['Unnamed: 0', 'time', 'summary', 'icon', 'precipIntensity',
       'precipProbability', 'temperature', 'apparentTemperature', 'dewPoint',
       'humidity', 'windSpeed', 'windBearing', 'cloudCover', 'uvIndex',
       'visibility', 'location', 'pressure', 'windGust', 'precipType', 'ozone',
       'precipAccumulation'],
      dtype='object')

weather['date']=pd.to_datetime(weather.time).dt.date
weather['hour']=pd.to_datetime(weather.time).dt.hour

In [9]:
weather['timestamp'] = weather.apply(lambda x: datetime.datetime.strptime(x['time'], '%Y-%m-%d %H:%M:%S'), axis = 1)

In [10]:
locations=list(weather.location.unique())
[i.upper() for i in locations]

['BOSA',
 'ENGATIVA',
 'TUNJUELITO',
 'KENNEDY',
 'FONTIBON',
 'CHAPINERO',
 'CIUDADBOLIVAR',
 'ANTONIO NARIÑO',
 'LA CANDELARIA',
 'PUENTE ARANDA',
 'RAFAEL URIBE',
 'BARRIOS UNIDOS',
 'SUBA',
 'SAN CRISTOBAL',
 'SUMAPAZ',
 'LOS MARTIRES',
 'SANTAFE',
 'TEUSAQUILLO',
 'USAQUEN',
 'USME']

In [11]:
# Column renaming
cols = ['x', 'y', 'object_id', 'form', 'accident_id', 'year' , 
        'address', 'severity', 'accident_type', 'borough_geo', 
        'borough', 'timestamp', 'civ', 'pk']
accidents.columns = cols
accidents.timestamp = pd.to_datetime(accidents.timestamp, infer_datetime_format=True)

In [12]:
accidents['date'] = accidents.timestamp.dt.date
accidents['month'] = accidents.timestamp.dt.month
accidents['hour'] = accidents.timestamp.dt.hour

In [13]:
accidents['day'] = accidents.timestamp.dt.day

In [36]:
accidents['x'] = round(accidents['x'], 6)
accidents['y'] = round(accidents['y'], 6)

In [14]:
accidents.head(3)

,x,y,object_id,form,accident_id,year,address,severity,accident_type,borough_geo,borough,timestamp,civ,pk,date,month,hour,day
0,-74.039690,4.759877,1001,A00728405,360471,2010,AK 18A-CL 182 58,SOLO DANOS,CHOQUE,USAQUEN,USAQUEN,2010-05-25 20:10:00+00:00,1007130.0,91019224.0,2010-05-25,5,20,25
1,-74.114296,4.615476,1002,A00408972,305838,2008,TR 49-3 02,SOLO DANOS,CHOQUE,PUENTE ARANDA,PUENTE ARANDA,2008-09-30 07:00:00+00:00,16004607.0,195361.0,2008-09-30,9,7,30
2,-74.105296,4.509792,1003,A000341903,4437952,2016,CL 80A-KR 1 SE 02,CON HERIDOS,CHOQUE,USME,USME,2016-02-27 16:20:00+00:00,5002841.0,149316.0,2016-02-27,2,16,27

In [37]:
accidents_2019=accidents[accidents['year']==2019].reset_index(drop=True)
accidents_2019.head()

,x,y,object_id,form,accident_id,year,address,severity,accident_type,borough_geo,borough,timestamp,civ,pk,date,month,hour,day
0,-74.134363,4.579297,327001,A000908434,10472514,2019,KR 26-CL 52B S 2,CON HERIDOS,CHOQUE,TUNJUELITO,TUNJUELITO,2019-01-11 14:20:00+00:00,6001128.0,232187.0,2019-01-11,1,14,11
1,-74.048819,4.665144,327002,A000908387,10472553,2019,CL 84-KR 8 2,SOLO DANOS,CHOQUE,CHAPINERO,CHAPINERO,2019-01-11 11:30:00+00:00,2000813.0,35700.0,2019-01-11,1,11,11
2,-74.173301,4.615589,327003,A000908334,10472522,2019,KR 80-CL 53A S 2,CON HERIDOS,CHOQUE,KENNEDY,KENNEDY,2019-01-11 23:20:00+00:00,8007967.0,245233.0,2019-01-11,1,23,11
3,-74.025068,4.725288,327004,A000907795,10472569,2019,KR 7-CL 150 2,SOLO DANOS,CHOQUE,USAQUEN,USAQUEN,2019-01-11 06:30:00+00:00,1003533.0,172513.0,2019-01-11,1,6,11
4,-74.080770,4.670083,327005,A000908264,10472515,2019,CL 68-KR 58 2,CON HERIDOS,CHOQUE,BARRIOS UNIDOS,BARRIOS UNIDOS,2019-01-10 07:20:00+00:00,12002817.0,224800.0,2019-01-10,1,7,10

In [39]:
pos=accidents_2019[['x','y','timestamp', 'date', 'month', 'day', 'hour']]
len(pos)
pos.head()

           x         y                 timestamp        date  month  day  hour
0 -74.134363  4.579297 2019-01-11 14:20:00+00:00  2019-01-11      1   11    14
1 -74.048819  4.665144 2019-01-11 11:30:00+00:00  2019-01-11      1   11    11
2 -74.173301  4.615589 2019-01-11 23:20:00+00:00  2019-01-11      1   11    23
3 -74.025068  4.725288 2019-01-11 06:30:00+00:00  2019-01-11      1   11     6
4 -74.080770  4.670083 2019-01-10 07:20:00+00:00  2019-01-10      1   10     7

In [38]:
# pos['x'] = round(pos['x'], 6)
# pos['y'] = round(pos['y'], 6)

In [18]:
pos['coords'] = pos[['x', 'y']].apply(lambda x: ', '.join((str(x['x']), str(x['y']))), axis = 1)

# pos['coords'] = pos[['x', 'y']].apply(lambda x: ', '.join((str(round(x['x'], 6)), str(round(x['y'], 6)))), axis = 1)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [19]:
pos

,x,y,timestamp,date,month,day,hour,coords
0,-74.134363,4.579297,2019-01-11 14:20:00+00:00,2019-01-11,1,11,14,"-74.134363, 4.579297"
1,-74.048819,4.665144,2019-01-11 11:30:00+00:00,2019-01-11,1,11,11,"-74.048819, 4.665144"
2,-74.173301,4.615589,2019-01-11 23:20:00+00:00,2019-01-11,1,11,23,"-74.173301, 4.615589"
3,-74.025068,4.725288,2019-01-11 06:30:00+00:00,2019-01-11,1,11,6,"-74.025068, 4.725288"
4,-74.080770,4.670083,2019-01-10 07:20:00+00:00,2019-01-10,1,10,7,"-74.08077, 4.670083"
5,-74.151311,4.572193,2019-01-11 09:20:00+00:00,2019-01-11,1,11,9,"-74.151311, 4.572193"
6,-74.142010,4.667770,2019-01-11 01:00:00+00:00,2019-01-11,1,11,1,"-74.14201, 4.66777"
7,-74.135317,4.599616,2019-01-09 23:48:00+00:00,2019-01-09,1,9,23,"-74.135317, 4.599616"
8,-74.135804,4.588874,2019-01-11 17:38:00+00:00,2019-01-11,1,11,17,"-74.135804, 4.588874"
9,-74.149876,4.687513,2019-01-10 16:30:00+00:00,2019-01-10,1,10,16,"-74.149876, 4.687513"
10,-74.092781,4.618428,2019-01-10 05:15:00+00:00,2019-01-10,1,10,5,"-74.092781, 4.618428"
11,-74.085183,4.736202,2019-01-11 03:40:00+00:00,2019-01-11,1,11,3,"-74.085183, 4.736202"
12,-74.115665,4.672517,2019-01-10 22:00:00+00:00,2019-01-10,1,10,22,"-74.115665, 4.672517"
13,-74.094338,4.648686,2019-01-11 06:30:00+00:00,2019-01-11,1,11,6,"-74.094338, 4.648686"
14,-74.138621,4.560379,2019-01-10 07:13:00+00:00,2019-01-10,1,10,7,"-74.138621, 4.560379"
15,-74.090326,4.741737,2019-05-14 21:10:00+00:00,2019-05-14,5,14,21,"-74.090326, 4.741737"
16,-74.112507,4.632656,2019-05-16 12:27:00+00:00,2019-05-16,5,16,12,"-74.112507, 4.632656"
17,-74.072432,4.584746,2019-05-14 13:10:00+00:00,2019-05-14,5,14,13,"-74.072432, 4.584746"
18,-74.102551,4.633255,2019-05-15 13:20:00+00:00,2019-05-15,5,15,13,"-74.102551, 4.633255"
19,-74.059798,4.647937,2019-05-17 19:20:00+00:00,2019-05-17,5,17,19,"-74.059798, 4.647937"
20,-74.060828,4.687646,2019-05-14 22:40:00+00:00,2019-05-14,5,14,22,"-74.060828, 4.687646"
21,-74.164504,4.596026,2019-07-19 03:46:00+00:00,2019-07-19,7,19,3,"-74.164504, 4.596026"
22,-74.164200,4.595534,2019-04-08 18:43:00+00:00,2019-04-08,4,8,18,"-74.1642, 4.595534"
23,-74.079797,4.734670,2019-06-12 05:30:00+00:00,2019-06-12,6,12,5,"-74.079797, 4.73467"
24,-74.142476,4.619137,2019-05-15 08:35:00+00:00,2019-05-15,5,15,8,"-74.142476, 4.619137"
25,-74.084894,4.737722,2019-07-27 07:20:00+00:00,2019-07-27,7,27,7,"-74.084894, 4.737722"
26,-74.164467,4.596029,2019-04-20 20:40:00+00:00,2019-04-20,4,20,20,"-74.164467, 4.596029"
27,-74.064036,4.681253,2019-06-01 22:36:00+00:00,2019-06-01,6,1,22,"-74.064036, 4.681253"
28,-74.177644,4.597124,2019-04-27 11:50:00+00:00,2019-04-27,4,27,11,"-74.177644, 4.597124"
29,-74.123200,4.603938,2019-07-18 13:31:00+00:00,2019-07-18,7,18,13,"-74.1232, 4.603938"
...,...,...,...,...,...,...,...,...
29090,-74.113438,4.711402,2019-12-02 12:45:00+00:00,2019-12-02,12,2,12,"-74.113438, 4.711402"
29091,-74.035448,4.820638,2019-11-30 19:20:00+00:00,2019-11-30,11,30,19,"-74.035448, 4.820638"
29092,-74.139038,4.562574,2019-11-30 15:15:00+00:00,2019-11-30,11,30,15,"-74.139038, 4.562574"
29093,-74.056441,4.718488,2019-12-03 22:10:00+00:00,2019-12-03,12,3,22,"-74.056441, 4.718488"
29094,-74.071237,4.590370,2019-12-02 16:30:00+00:00,2019-12-02,12,2,16,"-74.071237, 4.59037"
29095,-74.193093,4.621825,2019-12-02 17:47:00+00:00,2019-12-02,12,2,17,"-74.193093, 4.621825"
29096,-74.081369,4.627823,2019-11-29 11:00:00+00:00,2019-11-29,11,29,11,"-74.081369, 4.627823"
29097,-74.102000,4.567379,2019-12-03 05:30:00+00:00,2019-12-03,12,3,5,"-74.102, 4.567379"
29098,-74.100680,4.585426,2019-11-29 11:32:00+00:00,2019-11-29,11,29,11,"-74.10068, 4.585426"
29099,-74.094082,4.611333,2019-11-30 12:00:00+00:00,2019-11-30,11,30,12,"-74.094082, 4.611333"
29100,-74.034167,4.690831,2019-11-30 14:10:00+00:00,2019-11-30,11,30,14,"-74.034167, 4.690831"
29101,-74.115550,4.592227,2019-12-03 06:20:00+00:00,2019-12-03,12,3,6,"-74.11555, 4.592227"
29102,-74.128988,4.676439,2019-12-03 08:14:00+00:00,2019-12-03,12,3,8,"-74.128988, 4.676439"
29103,-74.102262,4.575392,2019-07-29 21:10:00+00:00,2019-07-29,7,29,21,"-74.102262, 4.575392"
29104,-74.152635,4.636510,2019-12-02 15:00:00+00:00,2019-12-02,12,2,15,"-74.152635, 4.63651"
29105,-74.085638,4.616469,2019-11-30 17:10:00+00:00,2019-11-30,11,30,17,"-74.085638, 4.616469"
29106,-74.029202,4.738137,2019-12-02 17:21:00+00:00,2019-12-02,12,2,17,"-74.029202, 4.738137"
29107,-74.044152,4.748769,2019-12-03 18:50:00+00:00,2019-12-03,12,3,18,"-74.044152, 4.748769"
29108,-74.048628,4.685001,2019-12-03 19:50:00+00:00,2019-12-03,12,3,19,"-74.048628, 4.685001"
29109,-74.142379,4.580467,2019-12-01 02:33:00+00:00,2019-12-01,12,1,2,"-74.142379, 4.580467"
29110,-74.046994,4.688915,2019-11-29 20:52:00+00:00,2019-11-29,11,29,20,"-74.046994, 4.688915"
29111,-74.029840,4.698323,2019-11-28 14:00:00+00:00,2019-11-28,11,28,14,"-74.02984, 4.698323"
29112,-74.109861,4.654703,2019-12-01 11:57:00+00:00,2019-12-01,12,1,11,"-74.109861, 4.654703"
29113,-74.107518,4.544366,2019-11-29 21:00:00+00:00,2019-11-29,11,29,21,"-74.107518, 4.544366"
29114,-74.047228,4.749488,2019-11-30 10:10:00+00:00,2019-11-30,11,30,10,"-74.047228, 4.749488"
29115,-74.135687,4.580801,2019-12-03 12:50:00+00:00,2019-12-03,12,3,12,"-74.135687, 4.580801"
29116,-74.084275,4.590371,2019-12-04 04:40:00+00:00,2019-12-04,12,4,4,"-74.084275, 4.590371"
29117,-74.097752,4.619585,2019-12-03 16:50:00+00:00,2019-12-03,12,3,16,"-74.097752, 4.619585"
29118,-74.174217,4.576242,2019-12-20 16:14:00+00:00,2019-12-20,12,20,16,"-74.174217, 4.576242"
29119,-74.129928,4.570335,2019-12-21 09:10:00+00:00,2019-12-21,12,21,9,"-74.129928, 4.570335"

In [20]:
pos = pos[['coords', 'hour', 'day', 'month']]
pos.head(2)

                 coords  hour  day  month
0  -74.134363, 4.579297    14   11      1
1  -74.048819, 4.665144    11   11      1

In [21]:
def days_in_month(year, month):
    return monthrange(year, month)[1]

In [22]:
t1 = datetime.datetime.now()

neg_df = pd.DataFrame(columns=['coords', 'hour', 'day', 'month'])
cols = pos.columns.tolist()
neg_list = []

for i in range (200):
# for i in range (len(pos)*3):
    
    #we randomly choose which column to randomize
    randcol = random.randint(0, 3)
    
    #sampling a row at random, which column will be modified
    neg = pos.sample()
    
    #sampling another random row, from which we take the value we're replacing in the potential negative sample ('neg')
    sample = pos.sample()
    neg[cols[randcol]] = sample[cols[randcol]].values[0]
    
    #check if 'neg' is part of positive samples:
    
    ncoords = neg['coords'].values[0]
    nhour = neg['hour'].values[0]
    nday = neg['day'].values[0]
    nmonth = neg['month'].values[0]
    
    if pos.loc[(pos['coords'] == ncoords) & (pos['hour'] == nhour) & (pos['day'] == nday) & (pos['month'] == nmonth)].empty: 

        neg_list.append(neg.values.tolist()[0])
      
    else:
        print('found coincidence/day out of month range')
        print(neg.values.tolist()[0])
    
    i += 1
    
neg_df = pd.DataFrame.from_records(neg_list, columns= ['coords', 'hour', 'day', 'month'])
t2 = datetime.datetime.now()

print(t2-t1)

found coincidence/day out of month range
['-74.070175, 4.604504', 13, 14, 3]
found coincidence/day out of month range
['-74.106684, 4.682308', 19, 25, 7]
found coincidence/day out of month range
['-74.117852, 4.680568', 7, 24, 4]
found coincidence/day out of month range
['-74.066862, 4.636441', 7, 14, 9]
found coincidence/day out of month range
['-74.188234, 4.636346', 18, 17, 2]
found coincidence/day out of month range
['-74.042172, 4.775209', 13, 3, 8]
found coincidence/day out of month range
['-74.150146, 4.617477', 14, 30, 7]
found coincidence/day out of month range
['-74.081442, 4.720515', 16, 10, 3]
0:00:02.644449

In [23]:
neg_df

                   coords  hour  day  month
0    -74.106542, 4.549809    10   14      9
1    -74.097564, 4.637799    11   23     11
2    -74.084945, 4.589338    12    9     11
3    -74.156486, 4.618785    14    3      6
4    -74.120879, 4.696506     4   18      3
5    -74.087022, 4.722932    21   24      4
6    -74.101594, 4.596576    13   30      7
7     -74.13214, 4.709141     6    6      8
8    -74.048865, 4.738826    19   29     11
9    -74.109623, 4.663118    12   11      3
10   -74.209896, 4.611039    14    3      8
11    -74.152594, 4.62967    20   23      4
12   -74.105082, 4.497227    17    3      5
13    -74.117875, 4.70493    15   22      3
14   -74.174631, 4.596777    12   12      9
15   -74.088163, 4.674035    11   17      5
16    -74.112888, 4.63693    17   19      5
17   -74.032497, 4.713623    12   17      4
18   -74.100542, 4.603442    19    6      6
19    -74.15042, 4.595554    11    3      5
20   -74.150883, 4.632335    23   24      7
21   -74.144721, 4.599037     9    3      7
22   -74.136802, 4.636675    21    6      3
23   -74.139282, 4.612067     6   16      9
24   -74.051435, 4.667843    14    3      5
25   -74.044303, 4.667006     5   29      4
26   -74.104412, 4.600379     5   30     12
27   -74.129745, 4.593751     8   16      9
28   -74.131177, 4.699933    19   20      4
29   -74.067768, 4.731596    15    2      6
..                    ...   ...  ...    ...
162  -74.098183, 4.742537    14   18      7
163  -74.073905, 4.606835    13   25      1
164  -74.167879, 4.630406    17   16      4
165  -74.090989, 4.613659    13    5      7
166  -74.125167, 4.680491    21   22      8
167  -74.135765, 4.659621    11    9      7
168  -74.047925, 4.723744    16   17      7
169  -74.099416, 4.739012    19    4      8
170  -74.109865, 4.627377    16   27      5
171  -74.069374, 4.725345    16    7     11
172  -74.154025, 4.632638    16   27      7
173  -74.165908, 4.621001    17   19      7
174   -74.10068, 4.749207    12   27     11
175   -74.07974, 4.734452    10   30      8
176  -74.100767, 4.656776    18    8      3
177  -74.160915, 4.624558     9   28      7
178  -74.098889, 4.608725    18    4      5
179  -74.089529, 4.695739     7    2      6
180  -74.135418, 4.693037    21   23      5
181  -74.109894, 4.596297    22   12      1
182  -74.098317, 4.606667     7   25      4
183  -74.162792, 4.625155    22   29      7
184  -74.028601, 4.707148     9   25      5
185  -74.112411, 4.667659    19   21      9
186  -74.108095, 4.650575    16   14      3
187  -74.043505, 4.682551     9    6     11
188  -74.039738, 4.700919    11   28      8
189  -74.138559, 4.558256    13   17      1
190   -74.140527, 4.60816    10   24      2
191  -74.071851, 4.638328     6    2      6

[192 rows x 4 columns]

In [24]:
neg_df['day_out_of_month_range'] = neg_df.apply(lambda x: x['day'] > days_in_month(2019, x['month']), axis = 1)

In [25]:
#example of a negative sample which 'day' value makes no sense given its 'month' value
neg_df[neg_df['day_out_of_month_range'] == True].head()

                  coords  hour  day  month  day_out_of_month_range
91  -74.077613, 4.657924    20   31      9                    True

In [26]:
#removing such samples
neg_df = neg_df[neg_df['day_out_of_month_range'] == False]

In [27]:
neg_df['timestamp'] = neg_df.apply(lambda x: datetime.datetime(2019, x['month'], x['day'], x['hour']), axis = 1)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [28]:
neg_df

,coords,hour,day,month,day_out_of_month_range,timestamp
0,"-74.106542, 4.549809",10,14,9,False,2019-09-14 10:00:00
1,"-74.097564, 4.637799",11,23,11,False,2019-11-23 11:00:00
2,"-74.084945, 4.589338",12,9,11,False,2019-11-09 12:00:00
3,"-74.156486, 4.618785",14,3,6,False,2019-06-03 14:00:00
4,"-74.120879, 4.696506",4,18,3,False,2019-03-18 04:00:00
5,"-74.087022, 4.722932",21,24,4,False,2019-04-24 21:00:00
6,"-74.101594, 4.596576",13,30,7,False,2019-07-30 13:00:00
7,"-74.13214, 4.709141",6,6,8,False,2019-08-06 06:00:00
8,"-74.048865, 4.738826",19,29,11,False,2019-11-29 19:00:00
9,"-74.109623, 4.663118",12,11,3,False,2019-03-11 12:00:00
10,"-74.209896, 4.611039",14,3,8,False,2019-08-03 14:00:00
11,"-74.152594, 4.62967",20,23,4,False,2019-04-23 20:00:00
12,"-74.105082, 4.497227",17,3,5,False,2019-05-03 17:00:00
13,"-74.117875, 4.70493",15,22,3,False,2019-03-22 15:00:00
14,"-74.174631, 4.596777",12,12,9,False,2019-09-12 12:00:00
15,"-74.088163, 4.674035",11,17,5,False,2019-05-17 11:00:00
16,"-74.112888, 4.63693",17,19,5,False,2019-05-19 17:00:00
17,"-74.032497, 4.713623",12,17,4,False,2019-04-17 12:00:00
18,"-74.100542, 4.603442",19,6,6,False,2019-06-06 19:00:00
19,"-74.15042, 4.595554",11,3,5,False,2019-05-03 11:00:00
20,"-74.150883, 4.632335",23,24,7,False,2019-07-24 23:00:00
21,"-74.144721, 4.599037",9,3,7,False,2019-07-03 09:00:00
22,"-74.136802, 4.636675",21,6,3,False,2019-03-06 21:00:00
23,"-74.139282, 4.612067",6,16,9,False,2019-09-16 06:00:00
24,"-74.051435, 4.667843",14,3,5,False,2019-05-03 14:00:00
25,"-74.044303, 4.667006",5,29,4,False,2019-04-29 05:00:00
26,"-74.104412, 4.600379",5,30,12,False,2019-12-30 05:00:00
27,"-74.129745, 4.593751",8,16,9,False,2019-09-16 08:00:00
28,"-74.131177, 4.699933",19,20,4,False,2019-04-20 19:00:00
29,"-74.067768, 4.731596",15,2,6,False,2019-06-02 15:00:00
...,...,...,...,...,...,...
162,"-74.098183, 4.742537",14,18,7,False,2019-07-18 14:00:00
163,"-74.073905, 4.606835",13,25,1,False,2019-01-25 13:00:00
164,"-74.167879, 4.630406",17,16,4,False,2019-04-16 17:00:00
165,"-74.090989, 4.613659",13,5,7,False,2019-07-05 13:00:00
166,"-74.125167, 4.680491",21,22,8,False,2019-08-22 21:00:00
167,"-74.135765, 4.659621",11,9,7,False,2019-07-09 11:00:00
168,"-74.047925, 4.723744",16,17,7,False,2019-07-17 16:00:00
169,"-74.099416, 4.739012",19,4,8,False,2019-08-04 19:00:00
170,"-74.109865, 4.627377",16,27,5,False,2019-05-27 16:00:00
171,"-74.069374, 4.725345",16,7,11,False,2019-11-07 16:00:00
172,"-74.154025, 4.632638",16,27,7,False,2019-07-27 16:00:00
173,"-74.165908, 4.621001",17,19,7,False,2019-07-19 17:00:00
174,"-74.10068, 4.749207",12,27,11,False,2019-11-27 12:00:00
175,"-74.07974, 4.734452",10,30,8,False,2019-08-30 10:00:00
176,"-74.100767, 4.656776",18,8,3,False,2019-03-08 18:00:00
177,"-74.160915, 4.624558",9,28,7,False,2019-07-28 09:00:00
178,"-74.098889, 4.608725",18,4,5,False,2019-05-04 18:00:00
179,"-74.089529, 4.695739",7,2,6,False,2019-06-02 07:00:00
180,"-74.135418, 4.693037",21,23,5,False,2019-05-23 21:00:00
181,"-74.109894, 4.596297",22,12,1,False,2019-01-12 22:00:00
182,"-74.098317, 4.606667",7,25,4,False,2019-04-25 07:00:00
183,"-74.162792, 4.625155",22,29,7,False,2019-07-29 22:00:00
184,"-74.028601, 4.707148",9,25,5,False,2019-05-25 09:00:00
185,"-74.112411, 4.667659",19,21,9,False,2019-09-21 19:00:00
186,"-74.108095, 4.650575",16,14,3,False,2019-03-14 16:00:00
187,"-74.043505, 4.682551",9,6,11,False,2019-11-06 09:00:00
188,"-74.039738, 4.700919",11,28,8,False,2019-08-28 11:00:00
189,"-74.138559, 4.558256",13,17,1,False,2019-01-17 13:00:00
190,"-74.140527, 4.60816",10,24,2,False,2019-02-24 10:00:00
191,"-74.071851, 4.638328",6,2,6,False,2019-06-02 06:00:00

In [29]:
neg_df.drop(columns = ['day_out_of_month_range'], inplace = True)

C:\Users\User\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [30]:
neg_df

                   coords  hour  day  month           timestamp
0    -74.106542, 4.549809    10   14      9 2019-09-14 10:00:00
1    -74.097564, 4.637799    11   23     11 2019-11-23 11:00:00
2    -74.084945, 4.589338    12    9     11 2019-11-09 12:00:00
3    -74.156486, 4.618785    14    3      6 2019-06-03 14:00:00
4    -74.120879, 4.696506     4   18      3 2019-03-18 04:00:00
5    -74.087022, 4.722932    21   24      4 2019-04-24 21:00:00
6    -74.101594, 4.596576    13   30      7 2019-07-30 13:00:00
7     -74.13214, 4.709141     6    6      8 2019-08-06 06:00:00
8    -74.048865, 4.738826    19   29     11 2019-11-29 19:00:00
9    -74.109623, 4.663118    12   11      3 2019-03-11 12:00:00
10   -74.209896, 4.611039    14    3      8 2019-08-03 14:00:00
11    -74.152594, 4.62967    20   23      4 2019-04-23 20:00:00
12   -74.105082, 4.497227    17    3      5 2019-05-03 17:00:00
13    -74.117875, 4.70493    15   22      3 2019-03-22 15:00:00
14   -74.174631, 4.596777    12   12      9 2019-09-12 12:00:00
15   -74.088163, 4.674035    11   17      5 2019-05-17 11:00:00
16    -74.112888, 4.63693    17   19      5 2019-05-19 17:00:00
17   -74.032497, 4.713623    12   17      4 2019-04-17 12:00:00
18   -74.100542, 4.603442    19    6      6 2019-06-06 19:00:00
19    -74.15042, 4.595554    11    3      5 2019-05-03 11:00:00
20   -74.150883, 4.632335    23   24      7 2019-07-24 23:00:00
21   -74.144721, 4.599037     9    3      7 2019-07-03 09:00:00
22   -74.136802, 4.636675    21    6      3 2019-03-06 21:00:00
23   -74.139282, 4.612067     6   16      9 2019-09-16 06:00:00
24   -74.051435, 4.667843    14    3      5 2019-05-03 14:00:00
25   -74.044303, 4.667006     5   29      4 2019-04-29 05:00:00
26   -74.104412, 4.600379     5   30     12 2019-12-30 05:00:00
27   -74.129745, 4.593751     8   16      9 2019-09-16 08:00:00
28   -74.131177, 4.699933    19   20      4 2019-04-20 19:00:00
29   -74.067768, 4.731596    15    2      6 2019-06-02 15:00:00
..                    ...   ...  ...    ...                 ...
162  -74.098183, 4.742537    14   18      7 2019-07-18 14:00:00
163  -74.073905, 4.606835    13   25      1 2019-01-25 13:00:00
164  -74.167879, 4.630406    17   16      4 2019-04-16 17:00:00
165  -74.090989, 4.613659    13    5      7 2019-07-05 13:00:00
166  -74.125167, 4.680491    21   22      8 2019-08-22 21:00:00
167  -74.135765, 4.659621    11    9      7 2019-07-09 11:00:00
168  -74.047925, 4.723744    16   17      7 2019-07-17 16:00:00
169  -74.099416, 4.739012    19    4      8 2019-08-04 19:00:00
170  -74.109865, 4.627377    16   27      5 2019-05-27 16:00:00
171  -74.069374, 4.725345    16    7     11 2019-11-07 16:00:00
172  -74.154025, 4.632638    16   27      7 2019-07-27 16:00:00
173  -74.165908, 4.621001    17   19      7 2019-07-19 17:00:00
174   -74.10068, 4.749207    12   27     11 2019-11-27 12:00:00
175   -74.07974, 4.734452    10   30      8 2019-08-30 10:00:00
176  -74.100767, 4.656776    18    8      3 2019-03-08 18:00:00
177  -74.160915, 4.624558     9   28      7 2019-07-28 09:00:00
178  -74.098889, 4.608725    18    4      5 2019-05-04 18:00:00
179  -74.089529, 4.695739     7    2      6 2019-06-02 07:00:00
180  -74.135418, 4.693037    21   23      5 2019-05-23 21:00:00
181  -74.109894, 4.596297    22   12      1 2019-01-12 22:00:00
182  -74.098317, 4.606667     7   25      4 2019-04-25 07:00:00
183  -74.162792, 4.625155    22   29      7 2019-07-29 22:00:00
184  -74.028601, 4.707148     9   25      5 2019-05-25 09:00:00
185  -74.112411, 4.667659    19   21      9 2019-09-21 19:00:00
186  -74.108095, 4.650575    16   14      3 2019-03-14 16:00:00
187  -74.043505, 4.682551     9    6     11 2019-11-06 09:00:00
188  -74.039738, 4.700919    11   28      8 2019-08-28 11:00:00
189  -74.138559, 4.558256    13   17      1 2019-01-17 13:00:00
190   -74.140527, 4.60816    10   24      2 2019-02-24 10:00:00
191  -74.071851, 4.638328     6    2      6 2019-06-02 06:00:00

[191 rows x 5 columns]

In [31]:
#recovering 'x' and 'y' from 'coords'
neg_df['x'] = neg_df.apply(lambda x: float(x['coords'].split(", ")[0]), axis = 1)
neg_df['y'] = neg_df.apply(lambda x: float(x['coords'].split(", ")[1]), axis = 1)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [32]:
neg_df

,coords,hour,day,month,timestamp,x,y
0,"-74.106542, 4.549809",10,14,9,2019-09-14 10:00:00,-74.106542,4.549809
1,"-74.097564, 4.637799",11,23,11,2019-11-23 11:00:00,-74.097564,4.637799
2,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338
3,"-74.156486, 4.618785",14,3,6,2019-06-03 14:00:00,-74.156486,4.618785
4,"-74.120879, 4.696506",4,18,3,2019-03-18 04:00:00,-74.120879,4.696506
5,"-74.087022, 4.722932",21,24,4,2019-04-24 21:00:00,-74.087022,4.722932
6,"-74.101594, 4.596576",13,30,7,2019-07-30 13:00:00,-74.101594,4.596576
7,"-74.13214, 4.709141",6,6,8,2019-08-06 06:00:00,-74.132140,4.709141
8,"-74.048865, 4.738826",19,29,11,2019-11-29 19:00:00,-74.048865,4.738826
9,"-74.109623, 4.663118",12,11,3,2019-03-11 12:00:00,-74.109623,4.663118
10,"-74.209896, 4.611039",14,3,8,2019-08-03 14:00:00,-74.209896,4.611039
11,"-74.152594, 4.62967",20,23,4,2019-04-23 20:00:00,-74.152594,4.629670
12,"-74.105082, 4.497227",17,3,5,2019-05-03 17:00:00,-74.105082,4.497227
13,"-74.117875, 4.70493",15,22,3,2019-03-22 15:00:00,-74.117875,4.704930
14,"-74.174631, 4.596777",12,12,9,2019-09-12 12:00:00,-74.174631,4.596777
15,"-74.088163, 4.674035",11,17,5,2019-05-17 11:00:00,-74.088163,4.674035
16,"-74.112888, 4.63693",17,19,5,2019-05-19 17:00:00,-74.112888,4.636930
17,"-74.032497, 4.713623",12,17,4,2019-04-17 12:00:00,-74.032497,4.713623
18,"-74.100542, 4.603442",19,6,6,2019-06-06 19:00:00,-74.100542,4.603442
19,"-74.15042, 4.595554",11,3,5,2019-05-03 11:00:00,-74.150420,4.595554
20,"-74.150883, 4.632335",23,24,7,2019-07-24 23:00:00,-74.150883,4.632335
21,"-74.144721, 4.599037",9,3,7,2019-07-03 09:00:00,-74.144721,4.599037
22,"-74.136802, 4.636675",21,6,3,2019-03-06 21:00:00,-74.136802,4.636675
23,"-74.139282, 4.612067",6,16,9,2019-09-16 06:00:00,-74.139282,4.612067
24,"-74.051435, 4.667843",14,3,5,2019-05-03 14:00:00,-74.051435,4.667843
25,"-74.044303, 4.667006",5,29,4,2019-04-29 05:00:00,-74.044303,4.667006
26,"-74.104412, 4.600379",5,30,12,2019-12-30 05:00:00,-74.104412,4.600379
27,"-74.129745, 4.593751",8,16,9,2019-09-16 08:00:00,-74.129745,4.593751
28,"-74.131177, 4.699933",19,20,4,2019-04-20 19:00:00,-74.131177,4.699933
29,"-74.067768, 4.731596",15,2,6,2019-06-02 15:00:00,-74.067768,4.731596
...,...,...,...,...,...,...,...
162,"-74.098183, 4.742537",14,18,7,2019-07-18 14:00:00,-74.098183,4.742537
163,"-74.073905, 4.606835",13,25,1,2019-01-25 13:00:00,-74.073905,4.606835
164,"-74.167879, 4.630406",17,16,4,2019-04-16 17:00:00,-74.167879,4.630406
165,"-74.090989, 4.613659",13,5,7,2019-07-05 13:00:00,-74.090989,4.613659
166,"-74.125167, 4.680491",21,22,8,2019-08-22 21:00:00,-74.125167,4.680491
167,"-74.135765, 4.659621",11,9,7,2019-07-09 11:00:00,-74.135765,4.659621
168,"-74.047925, 4.723744",16,17,7,2019-07-17 16:00:00,-74.047925,4.723744
169,"-74.099416, 4.739012",19,4,8,2019-08-04 19:00:00,-74.099416,4.739012
170,"-74.109865, 4.627377",16,27,5,2019-05-27 16:00:00,-74.109865,4.627377
171,"-74.069374, 4.725345",16,7,11,2019-11-07 16:00:00,-74.069374,4.725345
172,"-74.154025, 4.632638",16,27,7,2019-07-27 16:00:00,-74.154025,4.632638
173,"-74.165908, 4.621001",17,19,7,2019-07-19 17:00:00,-74.165908,4.621001
174,"-74.10068, 4.749207",12,27,11,2019-11-27 12:00:00,-74.100680,4.749207
175,"-74.07974, 4.734452",10,30,8,2019-08-30 10:00:00,-74.079740,4.734452
176,"-74.100767, 4.656776",18,8,3,2019-03-08 18:00:00,-74.100767,4.656776
177,"-74.160915, 4.624558",9,28,7,2019-07-28 09:00:00,-74.160915,4.624558
178,"-74.098889, 4.608725",18,4,5,2019-05-04 18:00:00,-74.098889,4.608725
179,"-74.089529, 4.695739",7,2,6,2019-06-02 07:00:00,-74.089529,4.695739
180,"-74.135418, 4.693037",21,23,5,2019-05-23 21:00:00,-74.135418,4.693037
181,"-74.109894, 4.596297",22,12,1,2019-01-12 22:00:00,-74.109894,4.596297
182,"-74.098317, 4.606667",7,25,4,2019-04-25 07:00:00,-74.098317,4.606667
183,"-74.162792, 4.625155",22,29,7,2019-07-29 22:00:00,-74.162792,4.625155
184,"-74.028601, 4.707148",9,25,5,2019-05-25 09:00:00,-74.028601,4.707148
185,"-74.112411, 4.667659",19,21,9,2019-09-21 19:00:00,-74.112411,4.667659
186,"-74.108095, 4.650575",16,14,3,2019-03-14 16:00:00,-74.108095,4.650575
187,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551
188,"-74.039738, 4.700919",11,28,8,2019-08-28 11:00:00,-74.039738,4.700919
189,"-74.138559, 4.558256",13,17,1,2019-01-17 13:00:00,-74.138559,4.558256
190,"-74.140527, 4.60816",10,24,2,2019-02-24 10:00:00,-74.140527,4.608160
191,"-74.071851, 4.638328",6,2,6,2019-06-02 06:00:00,-74.071851,4.638328

In [40]:
negatives = neg_df.merge(accidents_2019[['borough', 'x', 'y']], on = ['x', 'y'])

In [41]:
negatives

,coords,hour,day,month,timestamp,x,y,borough
0,"-74.106542, 4.549809",10,14,9,2019-09-14 10:00:00,-74.106542,4.549809,RAFAEL URIBE URIBE
1,"-74.106542, 4.549809",10,14,9,2019-09-14 10:00:00,-74.106542,4.549809,RAFAEL URIBE URIBE
2,"-74.097564, 4.637799",11,23,11,2019-11-23 11:00:00,-74.097564,4.637799,TEUSAQUILLO
3,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SAN CRISTOBAL
4,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
5,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
6,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,CANDELARIA
7,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
8,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
9,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SAN CRISTOBAL
10,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
11,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
12,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,ANTONIO NARIÑO
13,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
14,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
15,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
16,"-74.084945, 4.589338",12,9,11,2019-11-09 12:00:00,-74.084945,4.589338,SANTA FE
17,"-74.156486, 4.618785",14,3,6,2019-06-03 14:00:00,-74.156486,4.618785,KENNEDY
18,"-74.120879, 4.696506",4,18,3,2019-03-18 04:00:00,-74.120879,4.696506,ENGATIVA
19,"-74.120879, 4.696506",4,18,3,2019-03-18 04:00:00,-74.120879,4.696506,ENGATIVA
20,"-74.087022, 4.722932",21,24,4,2019-04-24 21:00:00,-74.087022,4.722932,SUBA
21,"-74.101594, 4.596576",13,30,7,2019-07-30 13:00:00,-74.101594,4.596576,LOS MARTIRES
22,"-74.13214, 4.709141",6,6,8,2019-08-06 06:00:00,-74.132140,4.709141,ENGATIVA
23,"-74.13214, 4.709141",6,6,8,2019-08-06 06:00:00,-74.132140,4.709141,ENGATIVA
24,"-74.048865, 4.738826",19,29,11,2019-11-29 19:00:00,-74.048865,4.738826,SUBA
25,"-74.048865, 4.738826",19,29,11,2019-11-29 19:00:00,-74.048865,4.738826,USAQUEN
26,"-74.048865, 4.738826",19,29,11,2019-11-29 19:00:00,-74.048865,4.738826,USAQUEN
27,"-74.048865, 4.738826",19,29,11,2019-11-29 19:00:00,-74.048865,4.738826,USAQUEN
28,"-74.048865, 4.738826",19,29,11,2019-11-29 19:00:00,-74.048865,4.738826,USAQUEN
29,"-74.048865, 4.738826",19,29,11,2019-11-29 19:00:00,-74.048865,4.738826,USAQUEN
...,...,...,...,...,...,...,...,...
795,"-74.112411, 4.667659",19,21,9,2019-09-21 19:00:00,-74.112411,4.667659,ENGATIVA
796,"-74.112411, 4.667659",19,21,9,2019-09-21 19:00:00,-74.112411,4.667659,ENGATIVA
797,"-74.112411, 4.667659",19,21,9,2019-09-21 19:00:00,-74.112411,4.667659,FONTIBON
798,"-74.112411, 4.667659",19,21,9,2019-09-21 19:00:00,-74.112411,4.667659,FONTIBON
799,"-74.108095, 4.650575",16,14,3,2019-03-14 16:00:00,-74.108095,4.650575,FONTIBON
800,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
801,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
802,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
803,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
804,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
805,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
806,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
807,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
808,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
809,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
810,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
811,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
812,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
813,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
814,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
815,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
816,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
817,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
818,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
819,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
820,"-74.043505, 4.682551",9,6,11,2019-11-06 09:00:00,-74.043505,4.682551,USAQUEN
821,"-74.039738, 4.700919",11,28,8,2019-08-28 11:00:00,-74.039738,4.700919,USAQUEN
822,"-74.138559, 4.558256",13,17,1,2019-01-17 13:00:00,-74.138559,4.558256,CIUDAD BOLIVAR
823,"-74.140527, 4.60816",10,24,2,2019-02-24 10:00:00,-74.140527,4.608160,KENNEDY
824,"-74.071851, 4.638328",6,2,6,2019-06-02 06:00:00,-74.071851,4.638328,TEUSAQUILLO

In [151]:
weather

,Unnamed: 0,time,summary,icon,precipIntensity,precipProbability,temperature,apparentTemperature,dewPoint,humidity,...,cloudCover,uvIndex,visibility,location,pressure,windGust,precipType,ozone,precipAccumulation,timestamp
0,0,2017-10-27 05:00:00,Clear,clear-night,0.0000,0.00,7.00,6.22,6.99,1.00,...,0.00,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 05:00:00
1,1,2017-10-27 06:00:00,Clear,clear-night,0.0000,0.00,7.00,6.22,6.00,0.93,...,0.13,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 06:00:00
2,2,2017-10-27 07:00:00,Partly Cloudy,partly-cloudy-night,0.0000,0.00,7.00,6.22,6.99,1.00,...,0.44,0.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 07:00:00
3,3,2017-10-27 08:00:00,Partly Cloudy,partly-cloudy-night,0.0000,0.00,9.00,8.51,9.00,1.00,...,0.44,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 08:00:00
4,4,2017-10-27 09:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,10.00,10.00,9.99,1.00,...,0.75,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 09:00:00
5,5,2017-10-27 10:00:00,Partly Cloudy,partly-cloudy-night,0.0000,0.00,9.00,9.00,8.00,0.93,...,0.44,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 10:00:00
6,6,2017-10-27 11:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,9.00,7.95,8.00,0.93,...,0.44,0.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 11:00:00
7,7,2017-10-27 12:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,12.00,12.00,10.99,0.94,...,0.44,1.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 12:00:00
8,8,2017-10-27 13:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,14.00,14.00,10.99,0.82,...,0.44,3.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 13:00:00
9,9,2017-10-27 14:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,18.00,18.00,9.99,0.59,...,0.44,5.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 14:00:00
10,10,2017-10-27 15:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,19.01,19.01,10.99,0.60,...,0.44,8.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 15:00:00
11,11,2017-10-27 16:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,20.00,20.00,9.99,0.53,...,0.44,9.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 16:00:00
12,12,2017-10-27 17:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,20.00,20.00,9.00,0.49,...,0.44,9.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 17:00:00
13,13,2017-10-27 18:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,22.01,22.01,6.00,0.35,...,0.44,8.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 18:00:00
14,14,2017-10-27 19:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,18.00,18.00,12.00,0.68,...,0.44,6.0,6.994,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 19:00:00
15,15,2017-10-27 20:00:00,Mostly Cloudy,partly-cloudy-day,0.0000,0.00,17.00,17.00,10.99,0.68,...,0.75,3.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 20:00:00
16,16,2017-10-27 21:00:00,Partly Cloudy,partly-cloudy-day,0.0000,0.00,17.00,17.00,12.00,0.72,...,0.44,1.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 21:00:00
17,17,2017-10-27 22:00:00,Mostly Cloudy,partly-cloudy-day,0.0000,0.00,17.00,17.00,10.99,0.68,...,0.75,0.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 22:00:00
18,18,2017-10-27 23:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,15.00,15.00,13.00,0.88,...,0.75,0.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-27 23:00:00
19,19,2017-10-28 00:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,15.00,15.00,10.99,0.77,...,0.75,0.0,10.003,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-28 00:00:00
20,20,2017-10-28 01:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,12.00,12.00,10.99,0.94,...,0.75,0.0,5.002,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-28 01:00:00
21,21,2017-10-28 02:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,12.00,12.00,10.99,0.94,...,0.75,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-28 02:00:00
22,22,2017-10-28 03:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,13.00,13.00,12.00,0.94,...,0.75,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-28 03:00:00
23,23,2017-10-28 04:00:00,Partly Cloudy,partly-cloudy-night,0.0000,0.00,13.00,13.00,12.00,0.94,...,0.44,0.0,8.005,bosa,NaN,NaN,NaN,NaN,NaN,2017-10-28 04:00:00
24,0,2017-10-28 05:00:00,Partly Cloudy,partly-cloudy-night,0.0000,0.00,11.99,11.99,10.99,0.94,...,0.44,0.0,8.005,engativa,NaN,NaN,NaN,NaN,NaN,2017-10-28 05:00:00
25,1,2017-10-28 06:00:00,Partly Cloudy,partly-cloudy-night,0.0000,0.00,11.99,11.99,10.99,0.94,...,0.44,0.0,8.005,engativa,NaN,NaN,NaN,NaN,NaN,2017-10-28 06:00:00
26,2,2017-10-28 07:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,11.99,11.99,10.99,0.94,...,0.75,0.0,8.998,engativa,NaN,NaN,NaN,NaN,NaN,2017-10-28 07:00:00
27,3,2017-10-28 08:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,10.99,10.99,10.99,1.00,...,0.75,0.0,8.998,engativa,NaN,NaN,NaN,NaN,NaN,2017-10-28 08:00:00
28,4,2017-10-28 09:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,11.99,11.99,10.99,0.94,...,0.75,0.0,8.998,engativa,NaN,NaN,NaN,NaN,NaN,2017-10-28 09:00:00
29,5,2017-10-28 10:00:00,Mostly Cloudy,partly-cloudy-night,0.0000,0.00,11.99,11.99,10.99,0.94,...,0.75,0.0,8.998,engativa,NaN,NaN,NaN,NaN,NaN,2017-10-28 10:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226315,18,2019-12-31 23:00:00,Rain,rain,2.6944,0.34,11.34,11.40,11.34,1.00,...,1.00,0.0,7.260,usme,1012.9,2.24,rain,225.7,NaN,2019-12-31 23:00:00
226316,19,2020-01-01 00:00:00,Rain,rain,3.1725,0.36,11.40,11.50,11.40,1.00,...,1.00,0.0,6.121,usme,1013.6,1.90,rain,224.7,NaN,2020-01-01 00:00:00
226317,20,2020-01-01 01:00:00,Rain,rain,2.6522,0.36,11.07,11.12,11.07,1.00,...,1.00,0.0,7.316,usme,1013.5,2.09,rain,225.9,NaN,2020-01-01 01:00:00
226318,21,2020-01-01 02:00:00,Rain,rain,3.1982,0.39,10.61,10.61,10.61,1.00,...,1.00,0.0,8.169,usme,1015.5,2.29,rain,226.5,NaN,2020-01-01 02:00:00
226319,22,2020-01-01 03:00:00,Rain,rain,2.7780,0.38,10.00,10.00,10.00,1.00,...,1.00,0.0,16.093,usme,1015.9,2.67,rain,227.1,NaN,2020-01-01 03:00:00
226320,23,2020-01-01 04:00:00,Possible Light Rain,rain,2.0938,0.38,9.76,9.76,9.76,1.00,...,0.99,0.0,16.093,usme,1016.1,2.97,rain,227.6,NaN,2020-01-01 04:00:00
226321,0,2019-12-30 05:00:00,Overcast,cloudy,0.2748,0.20,11.41,11.41,8.82,0.84,...,0.98,0.0,16.093,usaquen,1016.3,1.71,rain,231.9,NaN,2019-12-30 05:00:00
226322,1,2019-12-30 06:00:00,Overcast,cloudy,0.1357,0.15,11.25,11.25,8.45,0.83,...,0.98,0.0,16.093,usaquen,1016.3,1.33,rain,232.3,NaN,2019-12-30 06:00:00
226323,2,2019-12-30 07:00:00,Overcast,cloudy,0.0793,0.09,11.33,11.33,8.45,0.82,...,0.99,0.0,16.093,usaquen,1015.1,1.38,rain,234.1,NaN,2019-12-30 07:00:00
226324,3,2019-12-30 08:00:00,Overcast,cloudy,0.1847,0.15,11.13,11.13,8.72,0.85,...,0.98,0.0,16.093,usaquen,1015.3,1.36,rain,233.9,NaN,2019-12-30 08:00:00
226325,4,2019-12-30 09:00:00,Overcast,cloudy,0.2430,0.17,10.38,10.38,8.24,0.87,...,0.98,0.0,16.093,usaquen,1015.0,1.37,rain,233.6,NaN,2019-12-30 09:00:00
226326,5,2019-12-30 10:00:00,Overcast,cloudy,0.1759,0.13,10.20,10.20,8.46,0.89,...,0.95,0.0,16.093,usaquen,1015.5,1.43,rain,233.6,NaN,2019-12-30 10:00:00
226327,6,2019-12-30 11:00:00,Overcast,cloudy,0.0631,0.07,10.45,10.45,9.03,0.91,...,0.88,0.0,16.093,usaquen,1016.1,1.50,rain,233.5,NaN,2019-12-30 11:00:00
226328,7,2019-12-30 12:00:00,Mostly Cloudy,partly-cloudy-day,0.0451,0.05,11.53,11.53,9.98,0.90,...,0.70,0.0,16.093,usaquen,1017.0,2.36,rain,233.7,NaN,2019-12-30 12:00:00
226329,8,2019-12-30 13:00:00,Mostly Cloudy,partly-cloudy-day,0.0269,0.05,13.52,13.52,11.64,0.88,...,0.86,2.0,16.093,usaquen,1014.7,2.71,rain,234.4,NaN,2019-12-30 13:00:00
226330,9,2019-12-30 14:00:00,Mostly Cloudy,partly-cloudy-day,0.0888,0.08,15.46,15.46,11.90,0.79,...,0.82,4.0,16.093,usaquen,1015.0,2.60,rain,235.6,NaN,2019-12-30 14:00:00
226331,10,2019-12-30 15:00:00,Mostly Cloudy,partly-cloudy-day,0.1698,0.11,18.43,18.43,12.08,0.67,...,0.81,6.0,16.093,usaquen,1014.2,2.44,rain,236.2,NaN,2019-12-30 15:00:00
226332,11,2019-12-30 16:00:00,Mostly Cloudy,partly-cloudy-day,0.4920,0.19,19.33,19.33,12.66,0.65,...,0.84,7.0,16.093,usaquen,1013.8,2.25,rain,235.7,NaN,2019-12-30 16:00:00
226333,12,2019-12-30 17:00:00,Mostly Cloudy,partly-cloudy-day,1.2140,0.24,19.58,19.58,13.08,0.66,...,0.87,7.0,11.939,usaquen,1013.3,2.05,rain,234.6,NaN,2019-12-30 17:00:00
226334,13,2019-12-30 18:00:00,Rain,rain,2.7023,0.29,17.44,17.44,13.50,0.78,...,0.93,7.0,6.711,usaquen,1013.1,2.00,rain,233.4,NaN,2019-12-30 18:00:00
226335,14,2019-12-30 19:00:00,Possible Light Rain,rain,1.7769,0.25,17.38,17.38,13.38,0.77,...,0.97,6.0,5.489,usaquen,1012.1,1.78,rain,228.7,NaN,2019-12-30 19:00:00
226336,15,2019-12-30 20:00:00,Possible Light Rain,rain,2.1734,0.27,17.06,17.06,13.51,0.80,...,0.98,4.0,6.832,usaquen,1011.9,1.75,rain,227.9,NaN,2019-12-30 20:00:00
226337,16,2019-12-30 21:00:00,Possible Light Rain,rain,2.1875,0.29,16.82,16.82,13.28,0.80,...,0.97,2.0,15.896,usaquen,1010.8,1.82,rain,227.1,NaN,2019-12-30 21:00:00
226338,17,2019-12-30 22:00:00,Possible Light Rain,rain,2.2596,0.32,15.89,15.89,13.05,0.83,...,0.97,0.0,13.227,usaquen,1011.2,2.05,rain,226.5,NaN,2019-12-30 22:00:00
226339,18,2019-12-30 23:00:00,Rain,rain,2.5799,0.34,14.89,14.89,13.14,0.89,...,0.97,0.0,8.319,usaquen,1012.3,2.33,rain,226.0,NaN,2019-12-30 23:00:00
226340,19,2019-12-31 00:00:00,Rain,rain,4.1438,0.39,14.29,14.35,14.07,0.99,...,0.96,0.0,4.849,usaquen,1013.4,1.32,rain,226.0,NaN,2019-12-31 00:00:00
226341,20,2019-12-31 01:00:00,Possible Light Rain,rain,1.9759,0.33,13.91,13.91,13.57,0.98,...,0.98,0.0,3.669,usaquen,1014.1,1.38,rain,225.8,NaN,2019-12-31 01:00:00
226342,21,2019-12-31 02:00:00,Possible Light Rain,rain,2.4206,0.36,13.93,13.93,12.80,0.93,...,0.99,0.0,4.715,usaquen,1014.8,1.62,rain,226.4,NaN,2019-12-31 02:00:00
226343,22,2019-12-31 03:00:00,Possible Light Rain,rain,2.3290,0.37,13.23,13.23,11.36,0.88,...,0.98,0.0,14.596,usaquen,1015.1,1.83,rain,227.2,NaN,2019-12-31 03:00:00
226344,23,2019-12-31 04:00:00,Possible Light Rain,rain,1.7662,0.37,12.89,12.89,10.68,0.86,...,0.99,0.0,12.361,usaquen,1015.1,1.97,rain,228.8,NaN,2019-12-31 04:00:00

In [140]:
# neg_df_weather = neg_df.merge(weather, left_on = 'timestamp', right_on = 'timestamp')

In [142]:
# neg_df_weather